* **Opções de Configuração**:

  Já imaginou quais opções de configuração estão disponíveis para você em arquivos
  como o ``app/config/config.yml``? Nesta seção, todas as configurações disponíveis
  serão separadas por chaves (ex.: ``framework``) que definem cada seção possível
  de sua configuração do Symfony2.

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* **Formulários e Validação**

  * :doc:`Form Field Type Reference</reference/forms/types>`
  * :doc:`Validation Constraints Reference </reference/constraints>`
  * :doc:`Twig Template Function Reference</reference/forms/twig_reference>`

* *Outras Áreas**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/YAML`
  * :doc:`/reference/requirements`
