* **Opções de Configuração**

  Já imaginou quais opções de configuração você tem disponível nos arquivos
  ``config/packages/*.yaml``? Nesta seção, todas as configurações disponíveis
  são divididas pela chave (ex., ``framework``) que define cada seção possível
  da sua configuração do Symfony.

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`
  * :doc:`debug </reference/configuration/debug>`

* :doc:`Configurando o Kernel </reference/configuration/kernel>`

* **Formulários e Validação**

  * :doc:`Referência de Tipos de Campo de Formulário </reference/forms/types>`
  * :doc:`Referência das Constraints de Validação </reference/constraints>`
  * :doc:`Referência de Funções e Variáveis de Templates Twig </reference/forms/twig_reference>`

* :doc:`Referência das Extensões do Twig (forms, filters, tags, etc) </reference/twig_reference>`

* **Outras Áreas**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/events`
  * :doc:`/reference/requirements`
