* **Opções de Configuração**:

  Já imaginou quais opções de configuração estão disponíveis para você em arquivos
  como o ``app/config/config.yml``? Nesta seção, todas as configurações disponíveis
  serão separadas por chaves (ex.: ``framework``) que definem cada seção possível
  de sua configuração do Symfony2.

  * :doc:`monolog </reference/configuration/monolog>`

* *Outras Áreas**

  * :doc:`/reference/requirements`
