* :doc:`/cookbook/assetic/index`

  * :doc:`/cookbook/assetic/asset_management`
  * :doc:`/cookbook/assetic/yuicompressor`
  * :doc:`/cookbook/assetic/jpeg_optimize`
  * :doc:`/cookbook/assetic/apply_to_option`

* :doc:`/cookbook/bundles/index`

  * :doc:`/cookbook/bundles/best_practices`
  * :doc:`/cookbook/bundles/inheritance`

* :doc:`/cookbook/cache/index`

  * :doc:`/cookbook/cache/varnish`

* :doc:`/cookbook/doctrine/index`

  * :doc:`/cookbook/doctrine/common_extensions`
  * :doc:`/cookbook/doctrine/reverse_engineering`
  * :doc:`/cookbook/doctrine/multiple_entity_managers`

* :doc:`/cookbook/email/index`

  * :doc:`/cookbook/email/email`
  * :doc:`/cookbook/email/dev_environment`
  * :doc:`/cookbook/email/spool`

* :doc:`/cookbook/event_dispatcher/index`

  * :doc:`/cookbook/event_dispatcher/class_extension`

* :doc:`/cookbook/form/index`

  * :doc:`/cookbook/form/data_transformers`
  * :doc:`/cookbook/form/use_virtuals_forms`

* :doc:`/cookbook/request/index`

  * :doc:`/cookbook/request/mime_type`

* :doc:`/cookbook/routing/index`

  * :doc:`/cookbook/routing/scheme`

* **symfony1**

  * :doc:`/cookbook/symfony1`

* :doc:`/cookbook/security/index`

  * :doc:`/cookbook/security/acl`
  * :doc:`/cookbook/security/form_login`

* :doc:`/cookbook/templating/index`

  * :doc:`/cookbook/templating/global_variables`

* :doc:`/cookbook/validation/index`

  * :doc:`/cookbook/validation/custom_constraint`

* :doc:`/cookbook/workflow/index`

  * :doc:`/cookbook/workflow/new_project_git`
