* **Código**

  * :doc:`Bugs </contributing/code/bugs>`
  * :doc:`Patches </contributing/code/patches>`
  * :doc:`Revisando Issues e Patches </contributing/community/reviews>`
  * :doc:`Manutenção </contributing/code/maintenance>`
  * :doc:`O Time Principal </contributing/code/core_team>`
  * :doc:`Segurança </contributing/code/security>`
  * :doc:`Testes </contributing/code/tests>`
  * :doc:`Compatibilidade com Versões Anteriores </contributing/code/bc>`
  * :doc:`Padrões de Codificação</contributing/code/standards>`
  * :doc:`Convenções de Código</contributing/code/conventions>`
  * :doc:`Git</contributing/code/git>`
  * :doc:`Licença </contributing/code/license>`

* **Documentação**

  * :doc:`Visão Geral </contributing/documentation/overview>`
  * :doc:`Formato </contributing/documentation/format>`
  * :doc:`Padrões da Documentação </contributing/documentation/standards>`
  * :doc:`Licença </contributing/documentation/license>`

* **Comunidade**

  * :doc:`Processo de Release </contributing/community/releases>`
  * :doc:`Revisões da Comunidade </contributing/community/reviews>`
  * :doc:`Outros Recursos </contributing/community/other>`
