* **Código de Conduta**

  * :doc:`/contributing/code_of_conduct/code_of_conduct`
  * :doc:`/contributing/code_of_conduct/reporting_guidelines`
  * :doc:`/contributing/code_of_conduct/care_team`
  * :doc:`/contributing/code_of_conduct/concrete_example_document`

* **Código**

  * :doc:`Bugs </contributing/code/bugs>`
  * :doc:`Patches </contributing/code/patches>`
  * :doc:`Revisando Issues e Patches </contributing/community/reviews>`
  * :doc:`Manutenção </contributing/code/maintenance>`
  * :doc:`A Equipe Central </contributing/code/core_team>`
  * :doc:`Segurança </contributing/code/security>`
  * :doc:`Testes </contributing/code/tests>`
  * :doc:`Compatibilidade com Versões Anteriores </contributing/code/bc>`
  * :doc:`Padrões de Codificação</contributing/code/standards>`
  * :doc:`Convenções de Código</contributing/code/conventions>`
  * :doc:`Git</contributing/code/git>`
  * :doc:`Licença </contributing/code/license>`

* **Documentação**

  * :doc:`Visão Geral </contributing/documentation/overview>`
  * :doc:`Formato </contributing/documentation/format>`
  * :doc:`Padrões de Documentação </contributing/documentation/standards>`
  * :doc:`Licença </contributing/documentation/license>`

* **Communidade**

  * :doc:`Processo de Lançamento </contributing/community/releases>`
  * :doc:`Comentários de Revisão Respeitosos </contributing/community/review-comments>`
  * :doc:`Revisões da Comunidade </contributing/community/reviews>`
  * :doc:`Outros Recursos </contributing/community/other>`
